version: '3.7'
services:
  samba-ad:
    image: dperson/samba:latest
    container_name: samba-ad
    cap_add:
      - SYS_ADMIN
    environment:
      - USER_NAME=administrator
      - USER_PASSWORD=Passw0rd!
      - DOMAIN=SKYSEC
      - REALM=SKYSEC.LOCAL
      - DNS_BACKEND=SAMBA_INTERNAL
    volumes:
      - ./data:/var/lib/samba
      - ./config/smb.conf:/etc/samba/smb.conf
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "88:88/tcp"
      - "389:389/tcp"
      - "464:464/tcp"
      - "636:636/tcp"
      - "3268:3268/tcp"
      - "3269:3269/tcp"
    restart: unless-stopped
